version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.11"
    rust: "latest"

sphinx:
  configuration: docs/source/conf.py

formats: all

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - validation