# This file is automatically generated by pyo3_stub_gen

import builtins
import typing

@typing.final
class Variant:
    r"""
    Represents a parsed HGVS variant.

    Provides access to the variant's accession, gene symbol, and coordinate type.
    Variants can be formatted back to HGVS strings or converted to JSON/dict representations.
    """

@typing.final
class VariantMapper:
    r"""
    High-level variant mapping engine.

    Coordinates mapping between different reference sequences (e.g., g. to c.)
    and projects cDNA variants onto protein sequences (c. to p.).
    Requires a DataProvider to retrieve transcript and sequence information.
    """

def parse(input: builtins.str) -> Variant:
    r"""
    Parses an HGVS string into a Variant object.

    Supported types include genomic (g.), coding cDNA (c.), non-coding (n.),
    mitochondrial (m.), and protein (p.) variants.

    Args:
        input: The HGVS string to parse.

    Returns:
        A Variant object.

    Raises:
        ValueError: If the HGVS string is malformed or unsupported.
    """
